### ISSUE TITLE
Cannot regenerate session id - headers already sent

### ISSUE THREAD

**Issue by dkns** [tmuras/moosh#105]
This happens with any command when given -v global option. 

PHP 5.5.9, current moodle dev 3.0

    ~/projects/moodle/master master
    ❯ moosh -n -v course-create
    Top Moodle dir: /home/daniel/projects/moodle/master
    Current working dir: /home/daniel/projects/moodle/master
    Relative Moodle dir: 
    PHP Warning:  session_regenerate_id(): Cannot regenerate session id - headers already sent in /home/daniel/projects/moodle/master/lib/classes/session/manager.php on line 462
    
    Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /home/daniel/projects/moodle/master/lib/classes/session/manager.php on line 462
    Not enough arguments provided. Please specify:
    shortname

**Comment by hermannkm** [comment]
Happens with my setup without any given option (except -n which i have to use since I cannot switch to www-data user):

Version: 3.1+ (2016052300.07)
Release: 07.07.2016
PHP: 7.0.4-7ubuntu2.1

moosh installed with git pull

````
root@server:/var/www/moodle# moosh -n theme-info
PHP Warning:  session_regenerate_id(): Cannot regenerate session id - session is not active in /var/www/moodle/lib/classes/session/manager.php on line 475

Warning: session_regenerate_id(): Cannot regenerate session id - session is not active in /var/www/moodle/lib/classes/session/manager.php on line 475
Course theme overrides disabled
No theme overrides on the course level

Category theme overrides disabled
No theme overrides on the category level

User theme overrides disabled
No theme overrides on the user level

Site themes:
default: campus
````

**Comment by hermannkm** [comment]
Suppressing error messages from the regenerate-statement can be simply done by adding a @ at the beginning of the command (line given in error message). Should not change program behavior and is much less annoying :-)
