### ISSUE TITLE
user CLI?

### ISSUE THREAD

**Issue by mgagliol** [tmuras/moosh#109]
Is MOOSH admin-only, or would it be useful for a user (to upload files or edit content from the command line)?

If not, are you aware of any other tool that would? 

Thanks a lot anyway..

Matteo

**Comment by tmuras** [comment]
You can try -u flag for moosh, see "Basic usage" section on http://moosh-online.com.

**Comment by mgagliol** [comment]
Thanks! But that seems to require access to the server, which I have not.. I use moodle as a teacher.

**Comment by tmuras** [comment]
Not really then - this tool is meant to be used by command line, meaning you have to have SSH access to your Moodle installation... sorry!
