### ISSUE TITLE
Add option for specifying plugin version for plugin-install

### ISSUE THREAD

**Issue by hcpss-banderson** [tmuras/moosh#111]
Right now I can't use moosh for deployment or automation because I cannot specify the exact version of a plugin to install with plugin-install.

If, on my staging environment, I install block_rss_plus with:

```
$ moosh plugin-install block_rss_plus 28
```
I will get version 2015060101 because that is the latest version released for Moodle 2.8. But if there is a release between the time I deployed to staging and the time I deployed to production then the same command may give me version 2015101400 on production, which is obviously not the version I tested.

So, what I am asking for is to option of specifying a version like this

```
$ moosh plugin-install block_rss_plus 28 2015060101
```

**Comment by hcpss-banderson** [comment]
Or maybe the plugin version should replace the moodle version. After all this command must be run on a bootstrapped moodle installation so the moodle version could be obtained implicitly.

**Comment by dkns** [comment]
Fixed in https://github.com/tmuras/moosh/commit/885c190e24f9a5469052ae0a1980a31587712371
