### ISSUE TITLE
Does Moosh work well on Moodle 3.0?

### ISSUE THREAD

**Issue by joaocc** [tmuras/moosh#124]
I saw in the plugins page that v3.0 is not yet supported.
Any plans?
Thx

**Comment by dkns** [comment]
It should work on 3.0. If you ran across any command that doesn't work on 3.0 just file an issue and we'll look at it.

**Comment by joaocc** [comment]
Thx. Would it be possible to update the version compatibility in moodle's plugin site (https://moodle.org/plugins/pluginversions.php?id=522)? thx
