### ISSUE TITLE
Moosh on Packagist

### ISSUE THREAD

**Issue by Mihailoff** [tmuras/moosh#133]
The git repo has been submitted to Packages an available at https://packagist.org/packages/tmuras/moosh

This will enable it to be installed as easy as `composer require tmuras/moosh`

@tmuras please contact me so I can add you as a maintainer there

**Comment by tmuras** [comment]
What do I need to do?

**Comment by Mihailoff** [comment]
On Packagist:
> This package is not auto-updated. Please set up the GitHub Service Hook for Packagist so that it gets updated whenever you push!

Why do you need Packagist? To have one more way of installing moosh via composer.

**Comment by Mihailoff** [comment]
Also `composer.json` definition is semi broken because a version `0.18` is being used https://github.com/tmuras/moosh/blob/master/composer.json#L5 for every tag so Composer thinks that it's `0.18` instead of `0.20`/`0.19`/etc. See https://github.com/Mihailoff/moosh/commit/943f6fa4ebffa5172c872c86347ccf7ffa78c368

**Comment by tmuras** [comment]
OK, that's done and I just created my account on packagist - can you add me as maintainer , the username is tmuras.

Thank you!

**Comment by Mihailoff** [comment]
@tmuras https://packagist.org/users/tmuras/
