### ISSUE TITLE
sql-dump failing intermittently with PHP warnings

### ISSUE THREAD

**Issue by bbusschots-mu** [tmuras/moosh#149]
We've been relying on moose's sql-dump function for years, and it's always been rock solid, but recently, and intermittently, this command has started to produce PHP errors which get injected into the SQL, making the dump invalid, and causing errors when we try to restore from the dumps.

This is the errant PHP output that is polluting the dumps:

`Warning: var_export does not handle circular references in /data/moodle2016/lib/classes/shutdown_manager.php on line 83`

**Comment by dkns** [comment]
This is happening because, IIRC, moodle is trying to log information coming from another thread. Did you change anything in your moodle configuration recently? Upgraded from <2.7 to 2.7> version?

**Comment by bbusschots-nuim** [comment]
@dkns we start our Moodle fresh each year, so we never update between major versions. We do however apply security updates, so our Moodle started at 2.8.1, and is now on what ever the latest 2.8 is.

**Comment by tmuras** [comment]
That's pretty bad - moosh was breaking the DB dumps. Sorry about that - would you have a way to confirm that latest version (not released yet) fixes it? I think that SQL dump should be much more reliable now.
