### ISSUE TITLE
Wrong deprecated message in course-enroll command

### ISSUE THREAD

**Issue by tsanecki** [tmuras/moosh#152]
- moosh version: 0.20
- moodle version: 2.5.2+
- database: MySQL 5.7.12
- php version: 7.0.4
- operating system: Ubuntu 16.04 LTS

### Actual behaviour

Using command course-enroll without -i (so that you have to provide user name instead of id), moosh prints "This command has been deprecated. Use user-list instead." message that probably belongs to user-getidbyname command (moosh is using the code for user-getidbyname internally?)

**Comment by tmuras** [comment]
Can not reproduce, maybe it's a confusion with moosh  course-enrolleduser
