### ISSUE TITLE
Composer Executed successfully, but GetOptionKit\OptionCollection not installed

### ISSUE THREAD

**Issue by bbusschots-nuim** [tmuras/moosh#155]
- moosh version: latest
- moodle version:
    - database:
- php version: 5.4.16
- operating system: RHEL 7

### Actual behaviour

```
[root@sandbox moosh]# ./moosh.php 
PHP Fatal error:  Class 'GetOptionKit\OptionCollection' not found in /usr/local/moosh/moosh.php on line 43

Fatal error: Class 'GetOptionKit\OptionCollection' not found in /usr/local/moosh/moosh.php on line 43
[root@sandbox moosh]#
```

### Expected behaviour

Moosh to execute

### Steps to reproduce

```
cd /usr/local
git clone https://github.com/tmuras/moosh.git
mkdir composer
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/composer
cd moosh
php /usr/local/composer/composer.phar update
ln -s /usr/local/moosh/moosh.php /bin/moosh
moosh
```

Composer thinks it installed all requirements:

```
[root@sandbox moosh]# php /usr/local/composer/composer.phar update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing corneltek/getoptionkit (dev-master 13a146e)
    Cloning 13a146e0f7b9161977332279dff894fa28c53168

  - Installing twig/twig (v1.18.2)
    Downloading: 100%         

  - Installing moodlehq/moodle-mod_newmodule (dev-master e1f112b)
    Cloning e1f112be8842291259ece87de3000cd5f0e18711

  - Installing jamiepratt/moodle-qtype_template (dev-master bf2b7bc)
    Cloning bf2b7bc641c1db5c4889e4cc78ee3c2225398871

  - Installing moodlehq/moodle-local_wstemplate (dev-master add2ad0)
    Cloning add2ad0949e72f025c0aad36c4b822e8c6479d3b

  - Installing danielneis/moodle-enrol_newenrol (dev-master master)
    Cloning master

  - Installing danielneis/moodle-block_newblock (dev-master 1fc89fb)
    Cloning 1fc89fb0845ad282426140feeb6bc3653efd1d7f

  - Installing danielneis/moodle-gradereport_newgradereport (dev-master 691f53a)
    Cloning 691f53a15de352c3fe25da03c001a97a76b18358

  - Installing yetanotherape/diff-match-patch (dev-master 0726dbb)
    Cloning 0726dbb4e59e68574326821c174013cf6fdfe20e

  - Installing danielneis/moodle-gradeexport_newgradeexport (dev-master 4d13e3f)
    Cloning 4d13e3f6e9f4f53d54d6e8ad348278248968412d

  - Installing danielneis/moodle-message_newprocessor (dev-master e2b82f0)
    Cloning e2b82f0776b13a30a79f4f20de89d597a15f58c5

  - Installing danielneis/moodle-availability_newavailability (dev-master 43198d6)
    Cloning 43198d6736931213ad223c8fd05881749baac22c

  - Installing symfony/finder (v2.8.7)
    Downloading: 100%         

  - Installing danielneis/moodle-local_newlocal (dev-master b9596bd)
    Cloning b9596bdd37963d312069a048c8d315c7592c1c24

Writing lock file
Generating autoload files
[root@sandbox moosh]#
```

How can I get Moosh to run on this server? Since composer gave no error message, I'm at a total loss!

**Comment by dkns** [comment]
Hi,

This is happening because for some weird reason composer pulls version of getoptionkit which has slightly different dir structure. I've updated getoptionkit to latest master and now it should fine. You can either: pull latest master and run composer update or edit moosh/vendor/composer/autoload_ps4.php and change

    'GetOptionKit\\' => array($vendorDir . '/corneltek/getoptionkit/src'),

to

    'GetOptionKit\\' => array($vendorDir . '/corneltek/getoptionkit/src/GetOptionKit/'),

If you update via composer let me know if you notice anything out of the ordinary.

**Comment by bbusschots-nuim** [comment]
@dkns - I can confirm that fixed the problem - thanks!

**Comment by joaocc** [comment]
I'm still getting this issue with:

- moosh clone from 0e5599b103982b5daebf38a4cf8f81ecf1ba40a2
- PHP 5.6.24

```
uuu@nlssr1 [/src/test/moosh]# mkdir -p /src/test/moosh-test
uuu@nlssr1 [/src/test/moosh]# pushd /src/test/moosh-test
/src/test/moosh-test /src/test/moosh ~/repo/cli/moosh
uuu@nlssr1 [/src/test/moosh-test]# git clone https://github.com/tmuras/moosh.git
Initialized empty Git repository in /src/test/moosh-test/moosh/.git/
remote: Counting objects: 6104, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 6104 (delta 2), reused 0 (delta 0), pack-reused 6091
Receiving objects: 100% (6104/6104), 8.03 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (3020/3020), done.
uuu@nlssr1 [/src/test/moosh-test]# mkdir composer
uuu@nlssr1 [/src/test/moosh-test]# curl -sS https://getcomposer.org/installer | php -- --install-dir=/src/test/moosh-test/composer
All settings correct for using Composer
Downloading 1.2.0...

Composer successfully installed to: /src/test/moosh-test/composer/composer.phar
Use it: php /src/test/moosh-test/composer/composer.phar
uuu@nlssr1 [/src/test/moosh-test]# cd moosh
uuu@nlssr1 [/src/test/moosh-test/moosh]# php /src/test/moosh-test/composer/composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing corneltek/getoptionkit (dev-master 13a146e)
    Cloning 13a146e0f7b9161977332279dff894fa28c53168

  - Installing twig/twig (v1.18.2)
    Loading from cache

  - Installing moodlehq/moodle-mod_newmodule (dev-master e1f112b)
    Cloning e1f112be8842291259ece87de3000cd5f0e18711

  - Installing jamiepratt/moodle-qtype_template (dev-master bf2b7bc)
    Cloning bf2b7bc641c1db5c4889e4cc78ee3c2225398871

  - Installing moodlehq/moodle-local_wstemplate (dev-master add2ad0)
    Cloning add2ad0949e72f025c0aad36c4b822e8c6479d3b

  - Installing danielneis/moodle-enrol_newenrol (dev-master master)
    Cloning master

  - Installing danielneis/moodle-block_newblock (dev-master 1fc89fb)
    Cloning 1fc89fb0845ad282426140feeb6bc3653efd1d7f

  - Installing danielneis/moodle-gradereport_newgradereport (dev-master 691f53a)
    Cloning 691f53a15de352c3fe25da03c001a97a76b18358

  - Installing yetanotherape/diff-match-patch (dev-master 0726dbb)
    Cloning 0726dbb4e59e68574326821c174013cf6fdfe20e

  - Installing danielneis/moodle-gradeexport_newgradeexport (dev-master 4d13e3f)
    Cloning 4d13e3f6e9f4f53d54d6e8ad348278248968412d

  - Installing danielneis/moodle-message_newprocessor (dev-master e2b82f0)
    Cloning e2b82f0776b13a30a79f4f20de89d597a15f58c5

  - Installing danielneis/moodle-availability_newavailability (dev-master 43198d6)
    Cloning 43198d6736931213ad223c8fd05881749baac22c

  - Installing symfony/finder (v2.8.8)
    Loading from cache

  - Installing danielneis/moodle-local_newlocal (dev-master b9596bd)
    Cloning b9596bdd37963d312069a048c8d315c7592c1c24

Writing lock file
Generating autoload files

uuu@nlssr1 [/src/test/moosh]# ./moosh.php
PHP Fatal error:  Class 'GetOptionKit\OptionCollection' not found in /tmp/moosh-test/moosh/moosh.php on line 43

Fatal error: Class 'GetOptionKit\OptionCollection' not found in /tmp/moosh-test/moosh/moosh.php on line 43

```

**Comment by joaocc** [comment]
This does not happen with commit 60b3f8dc4454bb4b74abbdfa58920a48479812d0

**Comment by hcpss-banderson** [comment]
Seems not to matter whether I use master or the 0.20 tag I still get verion 2.0.11 GetOptionKit which is broken.

Changing the GetOptionKit requirement in composer.json from "dev-master#whateverthecommitis" to "2.*" fixes the problem.

Why do we require a specific commit in the composer file? Why not just require 2.*?

**Comment by nadavkav** [comment]
@hcpss-banderson comment help me fix this issue. thanks.

**Comment by tmuras** [comment]
The latest commit d2c709b48836024ca923f3537d950ca985521b1c fixes the issue. I want to use #exacthash in composer file to make sure everyone gets exactly the same version of external libraries.

**Comment by hcpss-banderson** [comment]
@tmuras, can't that be accomplished by setting the version to 2.5.0? Hashes are pretty unusual and the [composer documentation advises against them](https://getcomposer.org/doc/04-schema.md#package-links).

Also, the commit you've chosen is not part of a stable release. As of this writing it is the latest commit and so is equivalent to dev-master when you probably want something more stable. The project page lists 2.5.0 as the latest stable release.

**Comment by tmuras** [comment]
I think you're right @hcpss-banderson - one day I will re-write the whole composer file and change into tags/releases.

**Comment by mwithheld** [comment]
This is still a problem - tested with the latest Moosh and composer versions:

1. Followed installation instructions (git clone + composer installer)

2. Test a simple moosh command -- works
$ <moosh-path>/moosh.php --verbose languages-update
...

3. Composer update
$ cd <moosh-path> && php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 10 updates, 0 removals
Writing lock file
Generating autoload files

4. Test the same simple moosh command -- fails
$ cd <moodle-path> && php <moosh-path>/moosh.php --verbose languages-update
PHP Fatal error:  Uncaught Error: Class 'GetOptionKit\OptionCollection' not found in <moosh-path>moosh.php:43
...

5. Do another composer update
$ cd <moosh-path> && php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 9 updates, 0 removals
  - Installing corneltek/getoptionkit (dev-master 3fd8490): Cloning 3fd84905bb from cache
Writing lock file
Generating autoload files

6. Test the same simple moosh command -- works
cd <moodle-path> && php <moosh-path>/moosh.php --verbose languages-update

7. Repeat ad-infinitum from step 3
