### ISSUE TITLE
Startdate is not set with course-create

### ISSUE THREAD

**Issue by abias** [tmuras/moosh#156]
- moosh version: 0.20
- moodle version: 3.0.x
    - database: Postgres
- php version: 5.5.21
- operating system: CentOS 6

### Steps to reproduce
Create a course with
moosh.php course-create --category 276 --fullname "foo" bar

### Actual behaviour
* The new course has startdate = 0 in the database
* If I open the course's settings in Moodle, the startdate widget shows the current date, but it does this only because the date is not set yet
* If I want to change the startdate afterwards, I have to run
moosh.php course-config-set <course-id> startdate <current-day>

### Expected behaviour
* The new course should have startdate = <current-day> in the database like it is set when I create a course with the Moodle GUI
* Ideally, the course-create command would get an additional parameter --startdate which can be used to set a startdate on course creation time

**Comment by tmuras** [comment]
I agree, it should set up today as a default - just like when using UI.

**Comment by abias** [comment]
Thanks, Tomasz!
