### ISSUE TITLE
Enable (and force) https for moosh-online.com website

### ISSUE THREAD

**Issue by pserwylo** [tmuras/moosh#168]
I was looking for instructions on how to install moosh, and it seems like moosh-online.com is the most authoritative source of such instructions. When following instructions that result in downloading and executing arbitrary code on a (potentially production) server, it is important that there is a high level of integrity around the instructions. Without https, there is no way to verify whether the instructions seen in the browser are from the legitimate moosh-online.com website or a malicious entity.
### Actual behaviour

Installation instructions on http://moosh-online.com are served over insecure HTTP.
### Expected behaviour

Installation instructions should be served over HTTPS.
### Steps to reproduce

Visit moosh-online.com and note that SSL is not configured.

**Comment by tmuras** [comment]
Very good point, thank you. Do you know if I have any free option for SSL available? Or do I need to get paid SSL certificate?

**Comment by pserwylo** [comment]
As of last year, https://letsencrypt.org/ was founded by Mozilla, Linux Foundation, EFF, and other prominent organisations to provide free domain validated SSL certificates for anybody. They should have some good tutorials on their website for how to get a certificate and then use it on your web server.

**Comment by tmuras** [comment]
Works well: https://test.moosh-online.com , I will switch the whole site soon.
