### ISSUE TITLE
remove writing to a home dir

### ISSUE THREAD

**Issue by iv-enovation** [tmuras/moosh#170]
- moosh version: 0.23
- moodle version: 3.1.2
    - database: mysql-server-5.5 5.5.52-0ubuntu0.14.04.1
- php version: PHP 5.5.9-1ubuntu4.20
- operating system: ubuntu14.04

### Actual behaviour
enovation@moodle:/mdl1.enovation.ie/www$  sudo -uwww-data /usr/bin/php /usr/bin/moosh admin-login;
Warning: my home directory: '/home/enovation' is not writable!
MoodleSession40181966:vt9g0r1eb1024t0cu9v2dt4tu2

### Expected behaviour
enovation@moodle:/mdl1.enovation.ie/www$  sudo -uwww-data /usr/bin/php /usr/bin/moosh admin-login;
MoodleSession40181966:vt9g0r1eb1024t0cu9v2dt4tu2

### Steps to reproduce
1. cd to moodle directory
2. run the above command

### description
Disregarding the ownership of files of a Moodle installation moosh seems to fail because of access permissions to Moodle data files, and they are always owned by a HTTP server system user. Because of this, it seems it's never a case moosh can be run without sudo
But when run with the sudo, moosh is trying to write to the user's home directory, and fails and issues the warning
And this is a problem, for scripts that depend on output. Surprisingly, the warning is printed on STDOUT
Please don't fix this by changing the output to STDERR. The whole idea of writing to the user directory seems wrong. If it's really needed, there must be a separate command for it that can be run by a correct user

**Comment by tmuras** [comment]
See #138 if sudo -H solves your problem

**Comment by iv-enovation** [comment]
Probably it does, but it is a workaround, as the one i already implemented. My point is that writing to the user home is a design flow

**Comment by tmuras** [comment]
Issue 1: Some of the commands require writing to home directory, so we depend on having write-able place to do so (~/.moosh), hence the check. The only improvement here would be to explicitly mark which commands write to the home directory and which don't - and do the check only for those that do.

Issue 2: The text " Warning: my home directory: '/home/enovation' is not writable!" is already printed to STDERR, check if you don't have a redirect from STDERR to STDOUT
