### ISSUE TITLE
Don't return error when no command was provided

### ISSUE THREAD

**Issue by Mihailoff** [tmuras/moosh#176]
- moosh version: moosh version 0.23 (master branch)
- php version: PHP 7.0.12 (cli) (built: Oct 18 2016 21:48:47) ( NTS )
- operating system: Alpine Linux

### Actual behaviour
Non zero error code on running without command or in help mode

### Expected behaviour
`moosh && echo $?` returns 0

Standard agreement in cli scripts, composer for example

`composer && echo $?` --> 0

### Steps to reproduce

`moosh || echo $?`

`moosh -h || echo $?`

**Comment by tmuras** [comment]
Makes more sense this way, thank you for reporting.
