### ISSUE TITLE
course-restore -- Restore pre-check failed

### ISSUE THREAD

**Issue by cyberjames** [tmuras/moosh#179]
- moosh version:0.23
- moodle version:3.1.1
    - database:5.5.40 
- php version:5.4.45
- operating system:AWS Linux

### Steps to reproduce
1. moosh course-restore /path/to/file.mbz 31
It produces the error below but when web ui, there is an option of "continue" button to skip that error. How todo that in moosh?

.......
.......
saving controller to db
calculating controller checksum xxxxxxxxxxxxxxxxxxxxxxxx
loading controller from db
Restore pre-check failed!
array(1) {
  ["warnings"]=>
  array(1) {
    [0]=>
    string(97) "The  role in the backup file cannot be mapped to any of the roles that you are allowed to assign."
  }
}

**Comment by marcoblancas** [comment]
pre-check warnigs before to restore can be skipped using **--ignore-warnings** https://moosh-online.com/commands/#course-restore.

This is working in moosh 1.15 and I can confirm that it also works in 1.5.

I think this issue can be closed.
