### ISSUE TITLE
Ubuntu PPA out-of-date (Trusty is last dist available)

### ISSUE THREAD

**Issue by dougti** [tmuras/moosh#182]
Hey,
 Would it be possible to update the PPA for the latest LTS, 16.04 Xenial?

Cheers,
 D

**Comment by tmuras** [comment]
It is updated but I keep in in older release to maintain 1 version only.
Please add the repository like this:

     sudo apt-add-repository 'deb http://ppa.launchpad.net/zabuch/ppa/ubuntu trusty main'
