### ISSUE TITLE
file-upload does not perform as described in http://moosh-online.com/commands/

### ISSUE THREAD

**Issue by rhmoult** [tmuras/moosh#184]
- moosh version: 0.23 (Defined in moosh/moosh.php line 40: define('MOOSH_VERSION', '0.23');
- moodle version: 3.3.2+ (Build: 20170316)
    - database: postgres PostgreSQL 9.5.6 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
- php version: 7.0.15-0ubuntu0.16.04.4
- operating system: Linux hostname 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Actual behaviour
Too many argument provided (2), the maximum is: 1

### Expected behaviour
Upload file /tmp/file.png to private area of user with id 1

### Steps to reproduce
sudo su -c "/opt/moosh/moosh.php file-upload /tmp/file.png 1" -s /bin/bash www-data

### Additional data
sudo su -c "/opt/moosh/moosh.php file-upload /tmp/file.png" -s /bin/bash www-data
PHP Notice:  Undefined variable: filepath in /opt/moosh/Moosh/Command/Moodle23/File/FileUpload.php on line 71

Notice: Undefined variable: filepath in /opt/moosh/Moosh/Command/Moodle23/File/FileUpload.php on line 71
Default exception handler: Cannot read file. Either the file does not exist or there is a permission problem. Debug:
Error code: storedfilecannotread
* line 1930 of /lib/filestorage/file_storage.php: file_exception thrown
* line 1487 of /lib/filestorage/file_storage.php: call to file_storage->add_file_to_pool()
* line 71 of /opt/moosh/Moosh/Command/Moodle23/File/FileUpload.php: call to file_storage->create_file_from_pathname()
* line 285 of /opt/moosh/moosh.php: call to Moosh\Command\Moodle23\File\FileUpload->execute()

!!! Cannot read file. Either the file does not exist or there is a permission problem. !!!

ls -al /tmp/file.png
-rw-r--r-- 1 www-data www-data 3409 Mar 28 12:41 /tmp/file.png

**Comment by tmuras** [comment]
You are right, the implementation is completely different, how could that happen :).
For now I will update the documentation to describe the command correctly.
