### ISSUE TITLE
course-restore -o overwrite doesn't appear to work

### ISSUE THREAD

**Issue by whanrott** [tmuras/moosh#185]
- moosh version: 0.23
- moodle version: 3.2
    - database: MySQL 5.5
- php version: 5.5.9, Zend Engine v2.5.0 with Zend OPcache v7.0.3,
- operating system: Ubuntu 14.04.5 LTS

### Actual behaviour
moosh -n course-restore -o ~/backup.mbz 147
Default exception handler: Can not find data record in database table course_categories. Debug: SELECT * FROM {course_categories} WHERE id = ?
[array (
  0 => '147',
)]
Error code: invalidrecord
* line 1526 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1502 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 44 of /home/whanrott/moosh-master/Moosh/Command/Moodle29/Course/CourseRestore.php: call to moodle_database->get_record()
* line 285 of /home/whanrott/moosh-master/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore->execute()

!!! Can not find data record in database table course_categories. !!!

### Expected behaviour
restore and over write courseid 147. Instead it appears to expect a course_category id. That doesn't seem correct.

**Comment by mwithheld** [comment]
I've had this problem too.  Our Moodle version is 3.1.5 on Linux/PHP 5.6.2x

> php /moosh/moosh.php course-restore --overwrite backup.mbz 34970
Default exception handler: Can not find data record in database table course_categories. Debug: SELECT * FROM {course_categories} WHERE id = :id
[array (
  'id' => '34970',
)]
Error code: invalidrecord
* line 1528 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1504 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 44 of moosh/Moosh/Command/Moodle29/Course/CourseRestore.php: call to moodle_database->get_record()
* line 285 of moosh/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore->execute()

!!! Can not find data record in database table course_categories. !!!
