### ISSUE TITLE
course-list doesn't seem to respect search parameter

### ISSUE THREAD

**Issue by NMCPaul** [tmuras/moosh#188]
- Moosh version: **0.24**
- Moodle version: **2.9.6**
    - Database: **MySQL**
- PHP version: **5.5.21**
- Operating system: **RHEL 6.7**

### Actual behaviour
All courses are displayed

### Expected behaviour
Only courses that match the search parameter provided should match.  I have verified that the search term appears in the Moodle course `shortname` field.

### Steps to reproduce
`php ~/moosh/moosh.php -n course-list 1403` displays every single course in my system, rather than the ones that just have the string `1403` in them.

**Comment by tmuras** [comment]
This is a problem with the documentation. I've changed that command: it used to use the argument to search the shortname & fullname. Now, the argument given is a SQL query fragment that simply gets injected after WHERE clause.

So to search, you do something like:

`moosh course-list 'fullname like "%2%"'`

**Comment by NMCPaul** [comment]
Ah!  Well that makes a lot of sense, then.  Thanks!

Is it restricter to just `fullname` and `shortname`?  Can I use it to search other course-specific fields, like `idnumber`?

**Comment by tmuras** [comment]
Yeah - have a look at https://moosh-online.com/commands/#course-list , I just updated it.
Thanks for reporting!

**Comment by nelsond143** [comment]
After this update the where clause seems to be broken for other options. ie:
sudo -u apache /var/www/moosh/moosh.php -v course-list -c 1
Top Moodle dir: /var/www/html/moodle
Current working dir: /var/www/html/moodle
Relative Moodle dir:
Processing command option 'help''
Processing command option 'idnumber''
Processing command option 'id''
Processing command option 'categorysearch''
'categorysearch' option is set on the command line to '1'
Processing command option 'visible''
'visible' option is set in the RC group defaults '1'
Processing command option 'empty''
Processing command option 'fields''
Processing command option 'output''
Command: list (course)
Options:
	help (): ''
	idnumber (): ''
	id (): ''
	categorysearch (): '1'
	visible (all): '1'
	empty (all): 'all'
	fields (): ''
	output (csv): 'csv'
Arguments:

SQL query run: SELECT c.id,c.category,c.shortname,c.fullname,c.visible FROM {course} c WHERE 1 AND c.category IN (?,?,?,?,?,?,?,?,?)
Params:
array (
  0 => 1,
  1 => 154,
  2 => 329,
  3 => 152,
  4 => 150,
  5 => 189,
  6 => 6104,
  7 => 169,
  8 => 153,
)
Default exception handler: Error reading from database Debug: ORA-00920: invalid relational operator
SELECT c.id,c.category,c.shortname,c.fullname,c.visible FROM m_course c WHERE 1 AND c.category IN (:o_param1,:o_param2,:o_param3,:o_param4,:o_param5,:o_param6,:o_param7,:o_param8,:o_param9)
[array (
  'o_param1' => 1,
  'o_param2' => 154,
  'o_param3' => 329,
  'o_param4' => 152,
  'o_param5' => 150,
  'o_param6' => 189,
  'o_param7' => 6104,
  'o_param8' => 169,
  'o_param9' => 153,
)]
Error code: dmlreadexception
* line 479 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
* line 1179 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
* line 88 of /var/www/moosh/Moosh/Command/Moodle26/Course/CourseList.php: call to oci_native_moodle_database->get_records_sql()
* line 285 of /var/www/moosh/moosh.php: call to Moosh\Command\Moodle26\Course\CourseList->execute()

!!! Error reading from database !!!

**Comment by tmuras** [comment]
Are you using Oracle?

**Comment by tezvi** [comment]
Just a quick thought, try comparing explicitly 1=1 in where clause, as Oracle might not implicitly convert number to boolean like MySQL does.

**Comment by nelsond143** [comment]
Yes, I am using oracle.
