### ISSUE TITLE
course-restore throwing a "setting_by_name_not_found" error

### ISSUE THREAD

**Issue by NMCPaul** [tmuras/moosh#189]
- Moosh version: **0.24**
- moodle version: **3.3+**
    - Database: **MySQL**
- PHP version: **7.0.15**
- Operating system: **Ubuntu 16.04 LTS**

### Actual behaviour
When I run
```php ~/moosh/moosh.php -n course-restore ../backup-moodle2-course-48500-cit119_\[1260_1703\]-20170607-0241.mbz 10143```
I get
```Creating new course to restore backup
Restoring (new course id,shortname,destination category): 47393,CIT119 [1260 1703],10143
Default exception handler: error/setting_by_name_not_found Debug: 
Error code: setting_by_name_not_found
$a contents: enrol_migratetomanual
* line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 97 of /backup/util/plan/base_task.class.php: call to base_plan->get_setting()
* line 159 of /root/moosh/Moosh/Command/Moodle29/Course/CourseRestore.php: call to base_task->get_setting()
* line 285 of /root/moosh/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore->execute()

!!! error/setting_by_name_not_found !!!
```
### Expected behaviour
Restoration of the course into the category with ID 10143.

### Steps to reproduce
The backup file is from Moodle 2.9.6, and the system I want to restore to is 3.3+.  We've been doing this successfully for a while via the web site, so I'm pretty sure the structure of the backups are compatible.

**Comment by BrunoMalaval** [comment]
Moosh version : 0.23 & 0.24
Moodle version : 3.3+
PHP : 7.0.10
MariaDB : 5.5.52
OS : RHEL 7.3

Hi,
I have the same error when restoring courses from Moodle 3.1.5 to 3.3
It works when I try to restore in 3.2.2
I Try with versions 0.23 and 0.24 from Moosh

Error is
Creating new course to restore backup
instantiating restore controller 6d4860724b1e9f9944dd8009cd1d3eb8
setting controller status to 100
loading backup info
loading controller plan
setting controller status to 300
applying restore defaults
**Unknown setting: questionbank**
setting controller status to 400
checking plan security
setting controller status to 600
saving controller to db
calculating controller checksum 91e9ec691f159184dc8b0ac7c4c818d9
loading controller from db
Restoring (new course id,shortname,destination category): 3, ED all_1,290
Default exception handler: error/setting_by_name_not_found Debug: 
Error code: setting_by_name_not_found
$a contents: enrol_migratetomanual
* line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 97 of /backup/util/plan/base_task.class.php: call to base_plan->get_setting()
* line 159 of /usr/local/moosh/Moosh/Command/Moodle29/Course/CourseRestore.php: call to base_task->get_setting()
* line 281 of /usr/local/moosh/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore->execute()

!!! error/setting_by_name_not_found !!!
!! 
Error code: setting_by_name_not_found
$a contents: enrol_migratetomanual !!
!! Stack trace: * line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 97 of /backup/util/plan/base_task.class.php: call to base_plan-&gt;get_setting()
* line 159 of /usr/local/moosh/Moosh/Command/Moodle29/Course/CourseRestore.php: call to base_task-&gt;get_setting()
* line 281 of /usr/local/moosh/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore-&gt;execute()

I notice there is an unknown setting : "questionbank" (see above)

Thanks a lot

Hav

**Comment by NMCPaul** [comment]
Looking at the Moodle Docs for the error (https://docs.moodle.org/33/en/error/moodle/setting_by_name_not_found):
```
Restoring an activity backup
This error is displayed when attempting to restore an activity backup to a new course. It is reported as MDL-24342.

Workaround: Restore the backup into an existing course (which can be newly created and empty).

Restoring a backup containing plugin data
Alternatively, the error may be displayed when attempting to restore a backup of a course which uses an additional plugin.

Workaround: Remove the usage of the additional plugin in the course then create a new course backup.
```
I'll need to do some digging to make sure that I have all the requisite plugins installed on both servers.

**Comment by BrunoMalaval** [comment]
Hi,

I just make another test

- installing a new fresh moodle instance ( moodle 3.1.6 / latest stable 3.1 version)
- no plugin on this instance
- create 1 teacher / 1 student / 1 course with only 1 document on the course and of course the 2 users.
- make a backup and try to restore it on my moodle 3.3
=> get exactly the same error
On the destination server (Moodle 3.3), I have several plugins because it's a working install for my future Moodle.
I'll make a last test with a new fresh 3.3 without plugins, but it's  a very strange behaviour
Thanks if you have an idea ...

**Comment by BrunoMalaval** [comment]
just another for today, and I stop for the week-end ... :-)

On my moodle 3.3 : 
- I restore a course through the web interface => all is ok , activities, users, ...
- make a backup
- try to restore it in the same server with moosh and get the same error
moosh version is the latest 0.24

**Comment by willend** [comment]
Hi there,

I confim the issue with a 'vanilla' Moodle 3.3 (no plugins) and a backup from a Moodle 3.1 system.

(Tagging my co-developer @climbcat so that we are all informed)

**Comment by yivi** [comment]
Confirming this same problem, as well. Latest moodle, latest moosh.

Problem seems to be located here:

CourseRestore.php:158
```
foreach ($tasks as &$task) {
            $setting = $task->get_setting('enrol_migratetomanual');
            $setting->set_value('1');
        } 
```
What is the "enrol_migratetomanual" setting? Can it be set manually somewhere to bypass this problem?

**Comment by BrunoMalaval** [comment]
Hi,

Another information, a similar bug (but perhaps any link), has been fixed this month on moodle

error : 

Error code: setting_by_name_not_found
$a contents: userinfo

link to the moodle tracker : [https://tracker.moodle.org/browse/MDL-59011]

**Comment by yivi** [comment]
Little "workaround".

Ugly, and I'm afraid that I'm breaking something I'm not aware of, but I really, really, **really** need to restore this course backups:

```
foreach ($tasks as &$task) {
        	try {
		        $setting = $task->get_setting( 'enrol_migratetomanual' );
		        $setting->set_value( '1' );
	        }
	        catch (\Exception $ex) {
        		echo "enrol_migratetomanual not found\n";
	        }
        }
```

Not in love with this, but  I'm able to restore the backup. So far, I haven't detected any breakage yet.

**Comment by tmuras** [comment]
Reproduced with completely empty course backup on 3.1 and restore on 3.3

`
Creating new course to restore backup
Restoring (new course id,shortname,destination category): 2,test1,1
Default exception handler: error/setting_by_name_not_found Debug: 
Error code: setting_by_name_not_found
$a contents: enrol_migratetomanual
* line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 97 of /backup/util/plan/base_task.class.php: call to base_plan->get_setting()
* line 159 of /home/tomasz/git/moosh/Moosh/Command/Moodle29/Course/CourseRestore.php: call to base_task->get_setting()
* line 285 of /home/tomasz/git/moosh/moosh.php: call to Moosh\Command\Moodle29\Course\CourseRestore->execute()

!!! error/setting_by_name_not_found !!!
`

**Comment by nadavkav** [comment]
Got the same issue :-(

**Comment by critch** [comment]
Wow, old bug. Been tracking the same problem here.  The trick I see is in Moosh,
Moosh/Command/Moodle29/Course/CourseRestore.php is trying to get setting enrol_migratetomanual on all tasks. 

I do not know what that is trying to accomplish. I do know that I can comment out the code with the for loop and it works.

I really suspect that solution is not ideal.
