### ISSUE TITLE
Help Moosh installation

### ISSUE THREAD

**Issue by 12336721** [tmuras/moosh#196]
Hello;

I need to install moosh I follow the steps of the page in https://moosh-online.com/ but running it in firefox generates error:

#!/usr/bin/env php 
Notice: Undefined variable: argv in /var/sentora/hostdata/zadmin/public_html/aula2/moosh/moosh.php on line 52

Catchable fatal error: Argument 1 passed to GetOptionKit\ContinuousOptionParser::parse() must be of the type array, null given, called in /var/sentora/hostdata/zadmin/public_html/aula2/moosh/moosh.php on line 52 and defined in /var/sentora/hostdata/zadmin/public_html/aula2/moosh/vendor/corneltek/getoptionkit/src/ContinuousOptionParser.php on line 139

Thanks for the help

**Comment by 12336721** [comment]
error File not found:
sudo apt-add-repository 'deb http://ppa.launchpad.net/zabuch/ppa/ubuntu trusty main'

**Comment by tmuras** [comment]
You can not use moosh via your web browser, it is a CLI (commandline) tool - that you run in a terminal (e.g. via SSH session to your server).

Regarding your error:
error: sudo: apt-add-repository: command not found

Install the command with:
sudo apt install software-properties-common

And try again.
