### ISSUE TITLE
https://moosh-online.com invalid ssl certificate

### ISSUE THREAD

**Issue by jkram** [tmuras/moosh#197]
- moosh version: na
- moodle version: na
    - database: na
- php version: na
- operating system: na

### Actual behaviour
When visiting https://moosh-online.com
SSL security certificate error in Chrome and Safari on Mac OS
Cannot visit non-https page of the web site
### Expected behaviour
SSL Should work, or fallback to http
### Steps to reproduce
Visit site with web browser on MacOS, and presumably with any browser on any OS.

**Comment by tmuras** [comment]
Thank you for reporting - fixed.
