### ISSUE TITLE
Block-add error on Moodle 3.5+

### ISSUE THREAD

**Issue by ticktoc** [tmuras/moosh#231]
- moosh version: 026
- moodle version: 3.5+
    - database: MySQL v5.7.23
- php version: 7.1.20
- operating system: Ubuntu 18.0.4LTS

Hi,
 I'm getting the following error when using block-add (moosh v0.26) on Moodle3.5+, mysql 5.7.23, php 7.1.20, Ubuntu 18.0.4LTS. Also tried it on another server running Moodle3.5+, mysql 5.7.19, php 7.0.25, Ubuntu 16.04.1 same error

Default exception handler: Error writing to database Debug: Field 'timecreated' doesn't have a default value
INSERT INTO mdl_block_instances (blockname,parentcontextid,showinsubcontexts,pagetypepattern,subpagepattern,defaultregion,defaultweight,configdata) VALUES(?,?,?,?,?,?,?,?)
[array (
  0 => 'gsb',
  1 => 343147,
  2 => 1,
  3 => 'course-view-*',
  4 => NULL,
  5 => 'Right',
  6 => '10',
  7 => '',
)]
Error code: dmlwriteexception
* line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
* line 98 of /usr/share/moosh/Moosh/Command/Moodle23/Block/BlockAdd.php: call to mysqli_native_moodle_database->insert_record()
* line 59 of /usr/share/moosh/Moosh/Command/Moodle23/Block/BlockAdd.php: call to Moosh\Command\Moodle23\Block\BlockAdd->blockAdd()
* line 291 of /usr/bin/moosh: call to Moosh\Command\Moodle23\Block\BlockAdd->execute()

!!! Error writing to database !!

**Comment by mwithheld** [comment]
This problem also happens on Moodle 3.8.1 with Moosh 0.30 (2019121900)

```
# moosh -n block-add course 2 integrityadvocate course-view-* side-post 0
Default exception handler: Error writing to database Debug: ERROR:  null value in column "timecreated" violates not-null constraint
DETAIL:  Failing row contains (20, integrityadvocate, 27, 0, 0, course-view-*, null, side-post, 0, , null, null).
INSERT INTO m_block_instances (blockname,parentcontextid,showinsubcontexts,pagetypepattern,subpagepattern,defaultregion,defaultweight,configdata) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id [array (
  'blockname' => 'integrityadvocate',
  'parentcontextid' => 27,
  'showinsubcontexts' => 0,
  'pagetypepattern' => 'course-view-*',
  'subpagepattern' => NULL,
  'defaultregion' => 'side-post',
  'defaultweight' => '0',
  'configdata' => '',
)]
Error code: dmlwriteexception
* line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 259 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 975 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 1023 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->insert_record_raw()
* line 98 of /moosh/Moosh/Command/Moodle23/Block/BlockAdd.php: call to pgsql_native_moodle_database->insert_record()
* line 59 of /moosh/Moosh/Command/Moodle23/Block/BlockAdd.php: call to Moosh\Command\Moodle23\Block\BlockAdd->blockAdd()
* line 351 of /moosh/moosh.php: call to Moosh\Command\Moodle23\Block\BlockAdd->execute()
```
