### ISSUE TITLE
Moosh 0.26 no longer works on php 5.

### ISSUE THREAD

**Issue by garthwilliamson** [tmuras/moosh#234]
- moosh version: 0.26
- moodle version: 2.7.20
    - database: postgres 9
- php version: 5.5.9
- operating system: Ubuntu 14.04.5 LTS

### Actual behaviour
Commit 35a40498dc4b34bfc9c6501bc371b487c69556ae introduces a dependency on php 7 (via phpparser). The previous version works fine on php 5. Older versions of moodle don't run on php 7.

### Expected behaviour
The parsing feature could be skipped on php < 7

### Steps to reproduce
Try to install moosh on php < 7

**Comment by tmuras** [comment]
I'm not sure if this should be fixed as PHP 5 is out of support now.

**Comment by tmuras** [comment]
I'd like to support as many PHP versions as possible, I don't have enough time to test it properly.
