### ISSUE TITLE
Bulk restore

### ISSUE THREAD

**Issue by sam-suresh** [tmuras/moosh#244]
- moosh version: 0.27
- moodle version: 3.6.1
    - database: MariaDb
- php version: 7.2.13
- operating system: CentOS

Hi

I want to restore multiple courses into existing courses (or into a category as new course). 

`moosh course-restore -e backup.mbz 3`

Is it possible to stack all courses names to be restored into a category instead one by one? Or what is the best way to restore multiple courses into a category? (I have over 800 courses).

Thank you.

**Comment by tmuras** [comment]
The way I do it is to create a simple bash script with each execution done separately, e.g.:
moosh course-restore -e backup1.mbz 3
moosh course-restore -e backup2.mbz 3
....
moosh course-restore -e backup800.mbz 3

This is much easier approach - for example you don't need to worry too much about any memory leaks - after each restore a new PHP process is started.

I also put "date" command between each restore to have an idea about time each one took, e.g.:
date
echo restoring backup1.mbz
moosh course-restore -e backup1.mbz 3

date
echo restoring backup2.mbz
moosh course-restore -e backup2.mbz 3
....

**Comment by sam-suresh** [comment]
Thank you @tmuras.

I find MOOSH is mentioned in several forum for bulk restore but is not documented. Adding it in the MOOSH website may be will help others. 

Cheers.

**Comment by tmuras** [comment]
Thank you for the suggestion @sam-suresh . I have added it to FAQ section https://moosh-online.com/faq/
