### ISSUE TITLE
Missing vendor/autoload.php 

### ISSUE THREAD

**Issue by Doogs75** [tmuras/moosh#245]
- moosh version: 0.27
- moodle version: 3.x
    - database: MSSQL
- php version: 7.2
- operating system: Windows

### Actual behaviour
Nothing. moosh.php returns to the command prompt

### Expected behaviour
Do something

### Steps to reproduce
create a fresh install (not upgrade, overwrite, etc). /vendor has no files (only moodlehq subfolder).

**Comment by davidscotson** [comment]
Running `composer install` will fill /vendor with the required dependencies and allow moosh.php to be used.

**Comment by tmuras** [comment]
Alternatively use the package from https://moodle.org/plugins/view.php?id=522 - which contains the vendor directory.
