### ISSUE TITLE
Docs out of sync with latest code

### ISSUE THREAD

**Issue by davidscotson** [tmuras/moosh#261]
I noticed that I couldn't find documentation for `theme-settings-import/export` on the website so did a check to see what other commands `moosh --help` returned that didn't show up in the docs.

These are in the tool but not on the website docs:
```
backup-info
base-path
cache-test
course-info
db-stats
delete-missingplugins
dev-langusage
file-check
file-hash-delete
info-context
lang-compare
theme-settings-export
theme-settings-import
top
user-login
userprofilefields-export
userprofilefields-import
```

And these are in the docs but not the tool:
```
course-enrolleduser
user-getidbyname
```

Issue #256 (bash completion not returning the full list) makes some of these useful tools hard to discover.

**Comment by davidscotson** [comment]
The ones is the docs but not in the tool, just say they're deprecated, so that's cool.

**Comment by tmuras** [comment]
cache-test is not implemented yet, so I skipped it.
I have now put the missing documentation for the others to https://moosh-online.com/commands .
Thank you very much David for checking it.
