### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by nadavkav** [tmuras/moosh#269]
- moosh version: 0.29
- moodle version: 3.7
    - database: MariaDB 10.1
- php version: 7.1
- operating system: CentOS 7.4

### Actual behaviour
We have a reverse-proxy in our institute and to get on the internet we need to use it, and I can not use the command moosh plugin-list to get an updated list of all Moodle plugins. (also, can not install new plugins)

### Expected behaviour
Be able to define a proxy server (and port) to get access to the internet

### Steps to reproduce
moosh plugin-list
...
PHP Warning:  fopen(https://download.moodle.org/api/1.3/pluglist.php): failed to open stream: Connection timed out in /var/www/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 36

**Comment by nadavkav** [comment]
I worked around it by adding the following code, before any call to: file_get_contents()
https://stackoverflow.com/a/17601295/374316

**Comment by tezvi** [comment]
Implemented here https://github.com/tmuras/moosh/pull/427
