### ISSUE TITLE
Error deleting users

### ISSUE THREAD

**Issue by juanfcomartin** [tmuras/moosh#272]
- moosh version: 0.29
- moodle version: 3.4
    - database: MySQL 5.7
- php version: 7.1
- operating system: Ubuntu Server 16.04

### Actual behaviour
I'm trying to use moosh in a script to remove all users (about 2700) from our Moodle as we want to move to LDAP authentication and start from scratch.
After my first try I got an error for several users and they weren't deleted (see attached file, sorry that some messages are in Spanish). I found that only the inactive users that were not enrolled in any course were deleted.
After using moosh in other script to reset all courses and unenroll all users I could narrow it down to about 500 users, but there is no way I can delete them. I always get an error as the one in the example attached.
[logmoosh.txt](https://github.com/tmuras/moosh/files/3427932/logmoosh.txt)
### Expected behaviour
The user being deleted.
### Steps to reproduce
moosh -v user-delete username

**Comment by tmuras** [comment]
Hi Juan,

I've tried to reproduce it - created a user, enrolled him into a course, added assignment and a grade. The deletion worked OK for me. This may be something specific to your Moodle installation or data.

If you can reproduce it on a clean Moodle installation and give me the steps, then most likely I can fix it. I have used Moodle 3.7.

**Comment by juanfcomartin** [comment]
Thank you for your reply Tomasz.

I'm afraid you're right, it's something specific to my Moodle installation. I've tried the deletion directly from the Site Administration and I got an error also.

Some time ago someone made an upgrade in an unorthodox way and some things got messed up.

Just a curiosity: is it normal that in the stack trace of the file I attached there are some calls to functions in php files from a Moodle version diferent that the one I'm running (3.4)? For instance:

PHP Stack trace:
PHP   1. {main}() /usr/bin/moosh:0
PHP   2. Moosh\Command\Moodle23\User\UserDelete->execute() /usr/bin/moosh:297
**PHP   3. user_delete_user() /usr/share/moosh/Moosh/Command/Moodle23/User/UserDelete.php:38**
PHP   4. delete_user() /var/www/campus/user/lib.php:214
PHP   5. grade_user_delete() /var/www/campus/lib/moodlelib.php:4049
PHP   6. grade_grade->delete() /var/www/campus/lib/gradelib.php:1498
PHP   7. grade_grade->delete() /var/www/campus/lib/grade/grade_grade.php:1034
PHP   8. grade_grade->notify_changed() /var/www/campus/lib/grade/grade_object.php:297

**Comment by tmuras** [comment]
Yes, that is normal. It just means that the command you're actually executing for Moodle 3.4 is the same one (the same code) as user-delete implemented for Moodle 2.3.

It's just the way I manage different version of the same command for different Moodle versions.

Good luck with cleaning that up, hopefully it won't be too much of an effort.

**Comment by juanfcomartin** [comment]
Thanks again for your reply and support.
Kind regards.
