### ISSUE TITLE
category-delete uses deprecated constructs

### ISSUE THREAD

**Issue by tmuras** [tmuras/moosh#273]
For Moodle 3.7:

++ Class coursecat is now alias to autoloaded class core_course_category, course_in_list is an alias to core_course_list_element. Class coursecat_sortable_records is deprecated without replacement. Do not include coursecatlib.php ++
* line 31 of /lib/coursecatlib.php: call to debugging()
* line 24 of /home/git/moosh/Moosh/Command/Moodle30/Category/CategoryDelete.php: call to require_once()
* line 330 of /home/git/moosh/moosh.php: call to Moosh\Command\Moodle30\Category\CategoryDelete->execute()
++ Class 'coursecat' has been renamed for the autoloader and is now deprecated. Please use 'core_course_category' instead. ++
* line 122 of /lib/classes/component.php: call to debugging()
* line ? of unknownfile: call to core_component::classloader()
* line 31 of /home/git/moosh/Moosh/Command/Moodle30/Category/CategoryDelete.php: call to spl_autoload_call()
* line 330 of /home/git/moosh/moosh.php: call to Moosh\Command\Moodle30\Category\CategoryDelete->execute()

**Comment by martygilbert** [comment]
I've written the code to fix this and issued a pull request a couple of months ago. This can be included whenever you all are ready.

**Comment by martygilbert** [comment]
I believe this can be closed now that PR #274 has been merged into master, correct @tmuras ?

**Comment by tmuras** [comment]
Yeah, that looks OK now - thanks!
