### ISSUE TITLE
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future.

### ISSUE THREAD

**Issue by christos312** [tmuras/moosh#275]
Hello, I am not sure if the below warning is showed because of PHP73 but I thought is a good idea t report it.

- moosh version: 0.29
- moodle version: 2019052001
    - database: mariadb
- php version: PHP 7.3.6
- operating system: CENTOS

### Actual behaviour
Running the cli command gives this warning

`Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/ec2-user/moosh/moosh.php on line 105
PHP Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/ec2-user/moosh/moosh.php on line 105
`
### Expected behaviour
No warnings or messages
### Steps to reproduce
Just run moosh

**Comment by kiklop74** [comment]
I just added pull request that fixes this one
https://github.com/tmuras/moosh/pull/279
