### ISSUE TITLE
Feature request: Sort courses in a category

### ISSUE THREAD

**Issue by benyovszky** [tmuras/moosh#287]
- moosh version: 0.30
- moodle version: 3.6.8
    - database: mariadb
- php version: 7.0
- operating system: Debian 9.11 (kernel 4.9.0-11-amd64)

### Actual behaviour
I could not find a solution for that.

### Expected behaviour
We need to sort alphabetically all courses within a category. Please investigate it, whether is it possible or not. This is the only step that we need to perform manually, all others are automated by moosh.

**Comment by tmuras** [comment]
Looks like it's working fine. The documentation: https://moosh-online.com/commands/#category-resortcourses .

The code is now in git, will be released in the next version.
