### ISSUE TITLE
activity-add quiz should allow completion params

### ISSUE THREAD

**Issue by mwithheld** [tmuras/moosh#290]
- moosh version:0.3
- moodle version:3.8
    - database:any
- php version:any
- operating system:any

### Actual behaviour
/var/www/html# moosh -n activity-add -n 'moosh test quiz #3' -o="--intro=\"Sample test description.\""  --completion=2 --completionview=1 --completiongrade=1 --completionpass=1 quiz 2;
Invalid option: --completion=2

### Expected behaviour
e.g.
moosh -n activity-add -n 'moosh test quiz #3' -o="--intro=\"Sample test description.\""  --completion=2 --completionview=1 --completiongrade=1 --completionpass=1 quiz 2;

should add a quiz with 

- Completion tracking=Show activity as complete when conditions are met
- Require view = Student must view this activity to complete it
- Require grade = Student must receive a grade to complete this activity  
- Require passing grade = 1

**Comment by drbean** [comment]
The quoting of the options (-o) should be as follows:

moosh -n activity-add -n 'moosh test quiz #3' -o="--intro=Sample test description. --completion=2 --completionview=1 --completiongrade=1 --completionpass=1" quiz 2

You don't need to quote the included options, which are separated by the ' --' strings.

Trying out that line, after enabling completion tracking, I see the above options being set in {quiz} and {course_modules}, but I don't see a completiongrade field and the completionpass field remains zero.

**Comment by tmuras** [comment]
This works for me with Moodle 3.7:

```
➜ moosh activity-add -o "--intro=Abc def. --completion=2 --completionview=1 --completionusegrade=1 --completionpass=1" -n QuizName4 quiz 2
12
```


![image](https://user-images.githubusercontent.com/695281/78504496-f6901600-776d-11ea-8865-b5c6daffd04a.png)

**Comment by tmuras** [comment]
I've updated the example in [the documentation](https://moosh-online.com/commands/#activity-add).
Please re-open if this is not working as expected.
