### ISSUE TITLE
block-add gives Undefined property $visible

### ISSUE THREAD

**Issue by christos312** [tmuras/moosh#309]
- moosh version: moosh version 0.30
- moodle version: Moodle version detected: 37
    - database: MARIADB
- php version: PHP 7.3.6
- operating system: CENTOS

### Actual behaviour

Running

`moosh -n block-add categorycourses 2 block_calendar_upcoming course-view-* side-post 0`

I get

```
PHP Notice:  Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677

Notice: Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677
PHP Notice:  Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677

Notice: Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677
PHP Notice:  Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677

Notice: Undefined property: stdClass::$visible in /moodle/course/classes/category.php on line 677
debug: courseid=92
debug: courseid=93
debug: courseid=94
```

It does not add the blocks.

### Expected behaviour

To add blocks to all courses in category with ID 2

**Comment by tmuras** [comment]
I've fixed the notice but basically the example is wrong. 
The correct name for the block is "calendar_upcoming" and not "block_calendar_upcoming".
The command will work even without the notice fix.
