### ISSUE TITLE
Input is not readable

### ISSUE THREAD

**Issue by MikasKrukauskas** [tmuras/moosh#312]
- moosh version: 0.32
- moodle version: 3.8
  - database: mysql Ver 8.0.19-10 for Linux on x86_64
- php version: 7.2.30
- operating system: Linux Centos 7

### Actual behaviour
if I try to import that file with a command moosh theme-settings-import boost_settings_1558197087.tar.gz I get an error saying Input file not readable . I run moosh as root user and permissions to this file is readable and also writeable 
### Expected behaviour
To import theme settings without any problems
### Steps to reproduce
moosh theme-settings-export
moosh theme-settings-import boost_settings_1558197087.tar.gz

**Comment by juanda99** [comment]
Same here with moosh verion 0.32 and php 7.3. 
Function is_readable($this->inputfilepath) returns false. tar.gz file has right permissions and I can uncompress it with tar -xf without issues.
However if I jump the if another error arrives: 

```
Warning: mkdir(): File exists in /usr/src/moosh/Moosh/Command/Moodle27/Theme/SettingsImport.php on line 53

Warning: unlink(/var/www/html/snap_settings_1558197087.tar): No such file or directory in /usr/src/moosh/Moosh/Command/Moodle27/Theme/SettingsImport.php on line 161
Invalid argument, /var/www/html/snap_settings_1558197087.tar cannot be found
```

**Comment by juanda99** [comment]
All my fault, fixed!

**Comment by tmuras** [comment]
Please try now with the latest code from git.
