### ISSUE TITLE
Theme settings import not working as expected on manual export

### ISSUE THREAD

**Issue by juanda99** [tmuras/moosh#316]
- moosh version: 0.32

- operating system: linux

If I manually tar files on linux by default it gets current dir ".". When I try to import my tar.gz theme file it can't extract . files. 
I guess it can be solved with:
RecursiveDirectoryIterator::SKIP_DOTS

See https://stackoverflow.com/questions/38843938/phardata-extractto-method-failed-to-extract-tar-gz-on-linux-environment?rq=1

**Comment by juanda99** [comment]
I've fixed it myself doing a tar like this: (getting file by file)
`find /init-scripts/snap_settings -type f -printf "%f\n" | xargs tar -zcf snap_settings.tar.gz -C /init-scripts/snap_settings`

**Comment by tmuras** [comment]
Please try now with the latest code from git.
