### ISSUE TITLE
course-restore: permit restoration on lower Moodle versions

### ISSUE THREAD

**Issue by patsej** [tmuras/moosh#317]
- moosh version: 0.32
- moodle version: 3.8

Restoring a backup from a lower Moodle version is possible thru the GUI.
For instance a backup created on Moodle 3.8.3+ can be restored on a 3.8.2. 
It is possible as long as we accept it by clicking on Continue in the Restore process.

### Actual behaviour

When using Moosh, it starts the restoration but at the end displays the warning
 "This backup file has been created with Moodle 3.8.3+ (...) and it's newer than your currently installed Moodle 3.8.2+ (...). This could cause some inconsistencies because backwards compatibility of backup files cannot be guaranteed."

A very basic course is created but nothing is restored.

### Expected behaviour

Create the course anyway.
For instance a -f option added on the command line could force the restoration. 

### Steps to reproduce

1. Create a backup on a Moodle.
2. In the directory of an older Moodle, run moosh course-restore on this backup

Thanks ;-)

**Comment by tmuras** [comment]
Please try with --ignore-warnings option.
I have updated https://moosh-online.com/commands/#course-restore to document it.

**Comment by patsej** [comment]
Hello Tomasz,

Thanks for this quick improvement!

Have a nice night! ;-)
Patrice
