### ISSUE TITLE
jamiepratt/moodle-qtype_TEMPLATE big letters no-go with Composer

### ISSUE THREAD

**Issue by drbean** [tmuras/moosh#335]
Composer has been threatening to disallow capital letters in packages for some time, and with 2.0.1, it is erroring out on 

        jamiepratt/moodle-qtype_TEMPLATE

Changing TEMPLATE to template in composer.json for the package name at line 85, and the require of dev-master at line 232 allowed me to install the other packages, but what that did to the jamiepratt package, I don't know.

**Comment by AdrianSanchezLopez** [comment]
Having the same problem here

**Comment by sadawie** [comment]
experiencing the same issue. https://github.com/tmuras/moosh/pull/336/files there is a PR for it.

**Comment by AdrianSanchezLopez** [comment]
That PR fixes it, so as a workaround for others:
`sed -i 's/TEMPLATE/template/g' /path-to-moosh/composer.json`
and then `php composer install` or `php composer update`
that should do the trick meanwhile it's properly fixed in this repository
