### ISSUE TITLE
Unable to determine branch version - Moodle 3.10

### ISSUE THREAD

**Issue by sstraser** [tmuras/moosh#343]
- moosh version: 0.32
- moodle version: Moodle 3.10+ (Build: 20201113)
    - database: 10.5.8-MariaDB
- php version: 7.4.12
- operating system: CentOS Linux release 7.9.2009

when I run moosh -p /var/www/html/moodle course--list 

this show, on Moodle 3.8 works ok

PHP Fatal error:  Uncaught Exception: Unable to determine branch version from '/var/www/html/moodle/version.php' in /var/www/moosh/includes/functions.php:147

Does moosh works with this version of Moodle?

Best Regards,
Samo

**Comment by piopi** [comment]
The regex here https://github.com/tmuras/moosh/blob/22b45e43563966fcdec8a039c7bc8c649bc6a90a/includes/functions.php#L141 , need to be modified to: `if (preg_match('/^\$branch\s+=\s+\'(\d.*)\'.*/', $line, $matches))`

**Comment by dashohoxha** [comment]
This was just fixed by this: https://github.com/tmuras/moosh/pull/344

**Comment by sstraser** [comment]
Hello,

thank you both for help, working now ;).

Best Regards,
Samo

**Comment by amenk** [comment]
The PPA doesn't have the recent version with that fix?
	 # sudo LANG=C apt install moosh
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	moosh is already the newest version (0.32-1).
