### ISSUE TITLE
Possible to support setting MUC ?

### ISSUE THREAD

**Issue by PePoDev** [tmuras/moosh#356]
I need to set MUC with memcached in moodle server cli not browser.

But I did't found anything for that.

This project can add command eg. `cache-config` for config MUC ?

**Comment by tmuras** [comment]
There is no such a command - but I see it would be quite useful to add one.
Any chance you can work on it?

**Comment by PePoDev** [comment]
My knowledge on Moodle and PHP is not good enough, But I will **try**.
