### ISSUE TITLE
category-import missing?!

### ISSUE THREAD

**Issue by proedie** [tmuras/moosh#363]
- moosh version: 0.36
- moodle version: 3.10

The command category-import seems to be missing from the newest version of Moosh. Is that intentional? If so, what is the replacement?

Keep up the good work and stay healthy.

Cheers

Proedie

**EDIT**: Okay, the file category-import.sh DOES exist, but it's not found by Moosh, nor is it listed in the help.

**Comment by klebann** [comment]
Here you can find usuage:
https://moosh-online.com/commands/#category-import

Here is the code:
https://github.com/tmuras/moosh/blob/master/Moosh/Command/Moodle26/Category/CategoryImport.php

Do you mean that the category-import is not listed, when you execute `moosh category` ?

**Comment by proedie** [comment]
Thank you, @klebann for the response. Sorry for not being clear enough.

This is what I mean: When I enterr `moosh category-import filename`, I get an error message. The help that is then printed on the screen does not contain the command:

![No_category_import_comand](https://user-images.githubusercontent.com/1160801/108212782-92c8ce80-712e-11eb-9ad6-b2fbacac55eb.png)

**Comment by klebann** [comment]
Thats weird. It's working for me.
```
~/moosh/moosh.php category-
category-config-set
category-create
category-delete
category-export
category-import
category-list
category-move
category-resortcourses
gradecategory-create
gradecategory-list
questioncategory-create
```

Maybe try update to newest version of moosh. Also go to the moosh root folder and run `composer dump`

**Comment by proedie** [comment]
It's the newest version straight from the repo. Sorry for the delays. Will check ``composer dump``
