### ISSUE TITLE
moodle-local_wstemplate

### ISSUE THREAD

**Issue by tststs** [tmuras/moosh#369]
Hello,

the package `moodlehq/moodle-local_wstemplate` is required via composer.
Problem is this repo does not exist.

404 - https://github.com/moodlehq/moodle-local_wstemplate

Is there any alternative? Was it maybe accidentally deleted or set to private by moodle?

Greetings

**Comment by jckoester** [comment]
Same here. Unfortunately this bug renders moosh unusable with moodle 3.10:

- install from git does not work, commenting out  https://github.com/moodlehq/moodle-local_wstemplate in composer.sjon leaves you without a lot of useful functions
- install from moodle-repo gives you an old version that isn't comaptible with 3.10

Any suggestions how to fix this?

**Comment by schmima** [comment]
I have the same problem, anyone know a workaround?

**Comment by sadawie** [comment]
same here and looking for alternative or other suggestions.

**Comment by haietza** [comment]
Same problem here, need to use for scripts on 3.10 please and thank you!

**Comment by phager-at** [comment]
The only workaround I know for now is to install it via ZIP Download from moodle.org, there you already have the composer dependencies prepacked and won't need to install them separately.

See: https://moosh-online.com/#Installation.from.Moodle.package

**Comment by jckoester** [comment]
That does not really help if you are running moodle 3.10 as you will then experience #347.

**Comment by phager-at** [comment]
> That does not really help if you are running moodle 3.10 as you will then experience #347.
> 
> _Edit:_ Downloading the updated `includes/functions.php` from git does seem to work though.

Sorry, I've been in a hurry and haven't read your comment, but it's good you were able to complete the workaround for 3.10! :+1:

**Comment by tmuras** [comment]
Hi, there are 2 new versions packaged on Moodle - https://moodle.org/plugins/pluginversions.php?id=522 . You can use them atm.
