### ISSUE TITLE
new command "file-check" does not work

### ISSUE THREAD

**Issue by orestesmas** [tmuras/moosh#371]
I updated recently to Moosh 1.0 and noticed that there is (at least) one interesting new command: `file-check`. However, when I try to execute it, Moosh complains about missing libraries (see actual behaviour below).

Is seems that Moosh search for /lib/setuplib.php file inside its code tree, but there's no lib/ directory into that tree...

- moosh version: 1.0 (from git master ff530d3bddaa)
- moodle version: 3.10 (Build: 20210325)
    - database: mariadb  Ver 15.1
- php version: PHP 7.3.19-1~deb10u1 (cli)
- operating system: Debian Buster (10.7)

### Actual behaviour

```
# moosh -p <my moodle path> file-check -s 1

PHP Warning:  file_get_contents(/home/moosh/config.php): failed to open stream: No such file or directory in /home/moosh/includes/functions.php on line 466

Warning: file_get_contents(/home/moosh/config.php): failed to open stream: No such file or directory in /home/moosh/includes/functions.php on line 466
PHP Notice:  Undefined variable: CFG in /home/moosh/includes/functions.php on line 472

Notice: Undefined variable: CFG in /home/moosh/includes/functions.php on line 472
PHP Warning:  Creating default object from empty value in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 44

Warning: Creating default object from empty value in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 44
PHP Notice:  Undefined property: stdClass::$dataroot in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 46

Notice: Undefined property: stdClass::$dataroot in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 46
PHP Warning:  require_once(/home/moosh/lib/setuplib.php): failed to open stream: No such file or directory in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 61

Warning: require_once(/home/moosh/lib/setuplib.php): failed to open stream: No such file or directory in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 61
PHP Fatal error:  require_once(): Failed opening required '/home/moosh/lib/setuplib.php' (include_path='.:/usr/share/php') in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 61

Fatal error: require_once(): Failed opening required '/home/moosh/lib/setuplib.php' (include_path='.:/usr/share/php') in /home/moosh/Moosh/Command/Moodle39/File/FileCheck.php on line 61
```

### Expected behaviour
Action executed without error

### Steps to reproduce
On a fresh moosh install, type
`# moosh -p <my moodle path> file-check -s 1`

**Comment by tmuras** [comment]
Looks like it can't find your Moodle installation. How when you you switch to Moodle directory first? If it's not installed globally then maybe you need to run /home/moosh/moosh.php file-check.

➜ cd /var/www/html/vanilla310 
➜ moosh file-check
Missing /opt/data/vanilla310/filedir/0c/51/0c5190a24c3943966541401c883eacaa20ca20cb
assignfeedback_editpdf / stamps "tick.png" 2021-01-04 10:31 / 2021-01-04 10:31

**Comment by orestesmas** [comment]
Hi Tomasz. Thanks for your suggestion, but it didn't work.

I've moosh installed in /home/moosh (with a symbolic link into /usr/local/bin/moosh pointing to it). My moodle install is at /home/moodle. If I switch to this directory and execute moosh I get:

```
PHP Warning:  require_once(HTML/QuickForm.php): failed to open stream: No such file or directory in /home/moodle/lib/formslib.php on line 41

Warning: require_once(HTML/QuickForm.php): failed to open stream: No such file or directory in /home/moodle/lib/formslib.php on line 41
PHP Fatal error:  require_once(): Failed opening required 'HTML/QuickForm.php' (include_path='.:/usr/share/php') in /home/moodle/lib/formslib.php on line 41

Fatal error: require_once(): Failed opening required 'HTML/QuickForm.php' (include_path='.:/usr/share/php') in /home/moodle/lib/formslib.php on line 41
```

Clearly, it doesn't find QuickForm.php because it's located into /home/moodle/lib/pear/HTML/ and this path is not into the PHP path.

If I edit /etc/php/7.3/cli/php.ini to add this path to the "include_path" variable, then I get:
```
Resetting core_component cache after core upgrade to version 2020110903.01
PHP Fatal error:  Interface 'cacheable_object' not found in /home/moodle/repository/lib.php on line 57

Fatal error: Interface 'cacheable_object' not found in /home/moodle/repository/lib.php on line 57
```

And then I don't know what to do next (my php knowledge is poor at best).

**Comment by jackawardls** [comment]
I cannot seem to run this command at all. Any ideas? Is it because I do not have it in PATH?
![image](https://user-images.githubusercontent.com/58561068/122435222-b9d5c680-cf8f-11eb-8dde-8677871aa477.png)

**Comment by jamatrucola** [comment]
Hello

I'm successfully using moosh for commands like course-delete and course-reset.  However, I tried to use file-check for the first time and I'm getting an error.  See below.  Curious if anyone has thoughts.  I executed the command from within my Moodle directory.

Thanks
Joe

```
$ php /bitnami/moodleMaint/moosh/moosh.php -v -n -t -p /bitnami/moodle file-check -s 1
Moodle version detected: 39
Top Moodle dir: /bitnami/moodle
Current working dir: /bitnami/moodle
Relative Moodle dir:
Processing command option 'help''
Processing command option 'stop''
'stop' option is set on the command line to '1'
Command: check (file)
Options:
        help (): ''
        stop (100): '1'
Arguments:

PHP Parse error:  syntax error, unexpected '<', expecting end of file in /bitnami/moodleMaint/moosh/includes/functions.php(480) : eval()'d code on line 1

Parse error: syntax error, unexpected '<', expecting end of file in /bitnami/moodleMaint/moosh/includes/functions.php(480) : eval()'d code on line 1

```

**Comment by tmuras** [comment]
@jamatrucola the issue is most likely caused by your config.php file.
Check if the first line contains <?php tag (and not just <? ).
