### ISSUE TITLE
category-export broken for Moodle 3.10

### ISSUE THREAD

**Issue by zweitbyte** [tmuras/moosh#390]
- moosh version: 1.3 
- moodle version: 3.10
    - database: postgressql 9.6 | 12.8
- php version: 7.1.x | 7.4.x
- operating system: MacOS | Debian

### Actual behaviour
Error thrown:

PHP Warning:  require_once(/moodle/lib/coursecatlib.php): failed to open stream: No such file or directory in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26

Warning: require_once(/moodle/lib/coursecatlib.php): failed to open stream: No such file or directory in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26
PHP Fatal error:  require_once(): Failed opening required '/moodle/lib/coursecatlib.php' (include_path='/moodle/lib/pear:.:/usr/share/php') in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26

Fatal error: require_once(): Failed opening required '/moodle/lib/coursecatlib.php' (include_path='/moodle/lib/pear:.:/usr/share/php') in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26
moodle@moodle3:~/scripts/moosh-1.3$ php moosh.php --moodle-path=/moodle category-export 0
PHP Warning:  require_once(/moodle/lib/coursecatlib.php): failed to open stream: No such file or directory in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26

Warning: require_once(/moodle/lib/coursecatlib.php): failed to open stream: No such file or directory in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26
PHP Fatal error:  require_once(): Failed opening required '/moodle/lib/coursecatlib.php' (include_path='/moodle/lib/pear:.:/usr/share/php') in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26

Fatal error: require_once(): Failed opening required '/moodle/lib/coursecatlib.php' (include_path='/moodle/lib/pear:.:/usr/share/php') in /scripts/moosh-1.3/Moosh/Command/Moodle39/Category/CategoryExport.php on line 26

### Expected behaviour
Export a XML structure of the category tree

### Steps to reproduce
php moosh.php --moodle-path=/path/to/moodle/trunk category-export 0

**Comment by tmuras** [comment]
Thank you!
