### ISSUE TITLE
config-get on PHP 8.1: Deprecated str_replace(): Passing null to parameter #3

### ISSUE THREAD

**Issue by ansonhoyt** [tmuras/moosh#440]
- moosh version: 1.11
- moodle version: 402
    - database: MySQL 8.0.33-0ubuntu0.22.04.2
- php version: 8.1.2-1ubuntu2.11
- operating system: Ubuntu 22.04.2 LTS

### Actual behaviour

A PHP deprecation warning (once on stderr and once on stdout)
```bash
ahoyt@mdl2:/opt/moodle$ sudo -u www-data moosh config-get core siteadmins
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/share/moosh/Moosh/MooshCommand.php on line 254

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/share/moosh/Moosh/MooshCommand.php on line 254
2
```

Also, seems like stderr ends up in stdout, so users can only suppress one of the warnings:
```
$ sudo -u www-data moosh config-get core siteadmins 2>/dev/null # Still shows one of the warnings
```
### Expected behaviour

No deprecation warnings

### Steps to reproduce

Each of these reproduces it for me:
```
sudo -u www-data moosh config-get core siteadmins
sudo -u www-data moosh config-get core
sudo -u www-data moosh user-list --id "username IN ('ahoyt')"
```

**Comment by andrewscaya** [comment]
Hello to the Moosh team!

I can confirm that this is an issue on PHP 8.1.

Many thanks for this great project!

Cheers!
