### ISSUE TITLE
Ubuntu PPA not updated for any releases within Ubuntu's "Standard Support" (only `trusty`)

### ISSUE THREAD

**Issue by ansonhoyt** [tmuras/moosh#459]
- moosh version: `>= 1.11-1`
- operating system: any Ubuntu releases after `trusty`

Thanks for this great utility. ❤️ There seems to be a gap in the release process.

See https://github.com/tmuras/moosh/pull/441

### Actual behaviour

All Moosh releases after `1.11-1` are getting published to the [Ubuntu PPA](https://launchpad.net/~zabuch/+archive/ubuntu/ppa) for `trusty`, but not for any newer Ubuntu releases.

Per [Ubuntu releases](https://wiki.ubuntu.com/Releases), `trusty`, `xenial` and `bionic` are only under ESM support at this point (not yet EOL), so most folks are needing to be on `focal` and `jammy` to get Ubuntu security updates.

### Expected behaviour

I don't see a policy on what Ubuntu versions Moosh aims to support, but I think it's common to see packages limiting support to LTS releases that are within Ubuntu's [standard support cycle](https://ubuntu.com/about/release-cycle). That should work for most folks.

**Comment by ansonhoyt** [comment]
@tmuras with many releases only getting published to [your PPA](https://launchpad.net/~zabuch/+archive/ubuntu/ppa) for `trusty`, it looks like the ["Installation from Ubuntu package" option](https://moosh-online.com/#Installation) isn't the best or maintained choice.

Would you recommend one of the three options? Are you using the "Installation from git"?

Thanks!

**Comment by tmuras** [comment]
It is a problem with my releases - that work of copying to different Ubuntu repositories is manual and in more than one step.
Installing from PPA is quite convenient and I know few people who use it, so I think there is a value in this.
I have copied the moosh - 1.17-1  package to other releases now, I will try to do the same in the future. If you see me doing something wrong here, open an issue straight away :).

**Comment by ansonhoyt** [comment]
Thanks so much! It is very convenient.

I'd poked around to see how the PPAs were built/released, just in case a PR would help. I didn't get too far...so I especially appreciate your maintenance update!

**Comment by tmuras** [comment]
I think I'll need to stick to the manual process :) But thanks for looking into it, much appreciated!
