### ISSUE TITLE
Allow country and city to be empty when creating a user

### ISSUE THREAD

**Issue by ianmcn** [tmuras/moosh#461]
### Actual behaviour
If you don't specify a city or country, it defaults to Szczecin PL. 

### Expected behaviour
Moodle does not require a city or country to be added, so not specifying one should leave it blank rather than put in fake information.

### Steps to reproduce
Create a user account without specifying city or country. User will be created with Szczecin PL.

**Comment by tmuras** [comment]
It is possible but a bit tricky - I have documented it under https://moosh-online.com/faq/#default-options-overwrite . Please let me know if that works for you!
