### ISSUE TITLE
Errors in activities dates when use moosh course_reset

### ISSUE THREAD

**Issue by BrunoMalaval** [tmuras/moosh#474]
- moosh version: 1.21
- moodle version: 4.3
- database: mysql  Ver 15.1 Distrib 10.3.35-MariaDB
- php version: PHP 8.0.27
- operating system: RHEL 8.8

Hi,

We use course_reset command and found missing option and a bug

First, help and web page for this command doesn't specify the 'reset_end_date' option, but it exists

### Actual behaviour

When we reset a course with reset_start_date (with or without reset_end_date) ,
dates are corrects for the course, but not for activities with start and end date

### Expected behaviour

Have corrects dates for activities

### Steps to reproduce

Here is my test :

I have a course with (dates in french , dd/mm/yy )
start date : 01/09/2023
end date : 30/06/2024

In this course, an assignment with dates
start date : 01/01/2024
end date : 30/04/2024

I reset the course with : 

moosh course-reset -s "reset_forum_all=1 reset_start_date=1725148800 reset_end_date=1751241600" 2327
(reset_start_date = 01/09/2024 / reset_end_date = 30/06/2025 )

For the course, it's ok but not for the assignment.
When I display the assignment, I have : 

![image](https://github.com/tmuras/moosh/assets/13904744/6ae289a3-7c18-473a-bd3e-cced4aeab70e)

and In the assignment settings

![image](https://github.com/tmuras/moosh/assets/13904744/1a674821-2d24-4d22-a085-b3350e4f7e90)

### A fix

This year, I have a student (apprentice) [ Mathias Kliem ] and I ask him to find a fix.
He do it, and make a fork at this URL

https://github.com/DNum-UHA/moosh

Thanks a lot and have a nice day

**Comment by tmuras** [comment]
Good luck to you and Mathias in fixing this. Definitely please share this or any other improvement with us :)

**Comment by BrunoMalaval** [comment]
Hi,
I've made a pull request about this issue

Have a good day
