### ISSUE TITLE
Creation of dynamic property in ChkDataDir.php

### ISSUE THREAD

**Issue by blink38** [tmuras/moosh#482]
- moosh version: 5d1e9ec1dbeb86f87fc5940414f63ba473f85f47
- moodle version: 4.4.1
    - database: mysql
- php version: 8.2.15
- operating system: debian bullseye

### Actual behaviour

When executing moosh, a Deprection is displayed 

`PHP Deprecated:  Creation of dynamic property Moosh\Command\Moodle39\Info\ChkDataDir::$filelist is deprecated in /opt/moosh/Moosh/Command/Moodle39/Info/ChkDataDir.php on line 18`

### Expected behaviour

no deprecation

### Steps to reproduce

run : 
```shell
moosh | head
```
will display :
```
PHP Deprecated:  Creation of dynamic property Moosh\Command\Moodle39\Info\ChkDataDir::$filelist is deprecated in /opt/moosh/Moosh/Command/Moodle39/Info/ChkDataDir.php on line 18

Deprecated: Creation of dynamic property Moosh\Command\Moodle39\Info\ChkDataDir::$filelist is deprecated in /opt/moosh/Moosh/Command/Moodle39/Info/ChkDataDir.php on line 18
moosh version 1.21
...
```

**Comment by martygilbert** [comment]
I believe this can be closed, thanks to #483.
