### ISSUE TITLE
Moodle 4.5 break cache commands

### ISSUE THREAD

**Issue by owngr** [tmuras/moosh#500]
- moosh version: 1.2.1
- moodle version: 4.5.0
    - database: 15.8
- php version: 8.3
- operating system: debian (docker)

### Actual behaviour
We use moosh to change cachestore between redis and filesystem at runtime. We usually run the following command on our test instance to ensure that it use the filesystem:

```
moosh --no-user-check cache-edit-mappings --application=default_application --session=default_session
```

As Moodle 4.5 is out, I tried to install it and the command now fails with the following error:
```
[07-Oct-2024 16:26:24 Europe/Berlin] PHP Warning:  require_once(/var/www/html/cache/locallib.php): Failed to open stream: No such file or directory in /opt/moosh/Moosh/Command/Moodle39/Cache/CacheEditMappings.php on line 39

Warning: require_once(/var/www/html/cache/locallib.php): Failed to open stream: No such file or directory in /opt/moosh/Moosh/Command/Moodle39/Cache/CacheEditMappings.php on line 39
[07-Oct-2024 16:26:24 Europe/Berlin] Default exception handler: Exception - Failed opening required '[dirroot]/cache/locallib.php' (include_path='[dirroot]/lib/pear:.:/usr/local/lib/php') Debug:
Error code: generalexceptionmessage
* line 39 of /opt/moosh/Moosh/Command/Moodle39/Cache/CacheEditMappings.php: Error thrown
* line 363 of /opt/moosh/moosh.php: call to Moosh\Command\Moodle39\Cache\CacheEditMappings->execute()

!!! Exception - Failed opening required '[dirroot]/cache/locallib.php' (include_path='[dirroot]/lib/pear:.:/usr/local/lib/php') !!!
```

I looked out in the changes of Moodle 4.5 what could be the cause and actually cache/lib.php and cache/locallib.php have been removed during a big refractor: 
https://tracker.moodle.org/browse/MDL-82158

The merge commit can be found here: https://github.com/moodle/moodle/commit/4f25ac10448fb645c53b98d98d59c5ad71b659cb

It might have broken other Cache command too, but I'm not sure which ones.

### Steps to reproduce
1. Install moosh on a 4.5 instance
2. Run the following command:
```
moosh --no-user-check cache-edit-mappings --application=default_application --session=default_session
```

**Comment by tmuras** [comment]
Please test in the latest release 1.25.

**Comment by owngr** [comment]
@tmuras I tested it on Moodle 4.5

* it works to change cache store when using filesystem as session handler
* it doesn't work when using redis as sessionhandler

```
Warning: session_set_save_handler(): Session save handler cannot be changed when a session is active in /var/www/html/lib/classes/session/redis.php on line 235
[18-Nov-2024 13:51:42 Europe/Berlin] Default exception handler: Setting up of redis session failed. Please notify the server administrator. Debug:
Error code: redissessionhandlerproblem
* line 237 of /lib/classes/session/redis.php: core\session\exception thrown
* line 750 of /lib/classes/session/redis.php: call to core\session\redis->init()
* line 688 of /lib/classes/session/redis.php: call to core\session\redis->init_redis_if_required()
* line 996 of /lib/classes/session/manager.php: call to core\session\redis->destroy()
* line 636 of /lib/classes/session/manager.php: call to core\session\manager::destroy()
* line 4078 of /lib/moodlelib.php: call to core\session\manager::login_user()
* line 303 of /opt/moosh/moosh.php: call to complete_user_login()
```

I think there will still be a problem, with the Moodle versions using 2 digits instead of 3 though. The command folder should have all versions with 3 digits starting with Moodle310.

**Comment by tmuras** [comment]
Just to make it clear - you are referring to problem with redis set as session handler in config.php - like https://github.com/tmuras/moosh/issues/503 ?
Why do you think the 2-digits folder name is the problem here?

The current issue is fixed (wrong file include), right? 

20:57 in /var/www/html/moodle45 
➜ sudo -u www-data ~/git/moosh/moosh.php cache-edit-mappings --application=default_application --session=redis1         
Config Mode Mappings:
MODE_APPLICATION: default_application
MODE_SESSION: redis1
MODE_REQUEST: default_request

Default mode mappings edited

20:57 in /var/www/html/moodle45 
➜ sudo -u www-data ~/git/moosh/moosh.php cache-edit-mappings --application=default_application --session=default_application
Config Mode Mappings:
MODE_APPLICATION: default_application
MODE_SESSION: default_application
MODE_REQUEST: default_request

Default mode mappings edited

**Comment by owngr** [comment]
Sorry for my writing:
* the fix work for Moodle cache-edit-mappings as long as redis isn't used like https://github.com/tmuras/moosh/issues/503 
* the 3 digits problem is something that is happening only when you try to implement add-redis-store for Moodle 4.5.

The wrong file include is not visible on cache-edit-mappings, because cache-edit-mappings doesn't have a Moodle 310 version.

But for add-redis-store, it's a different story (because it has a 310 version):
1. here it pick up the $branch variable  https://github.com/tmuras/moosh/blob/master/includes/functions.php#L124-L141 this will return 405
2. Then here https://github.com/tmuras/moosh/blob/master/includes/functions.php#L152-L163 it will generate the versions from 19 to 405 so this will return [19, 20, .. ,45,..,310,405]
3. Then when Moosh has to choose a version it will use 310 instead of 45 as 310 is the higher supported version for add-redis-store and there is no Moodle405 folder.

**Why was it not detected before ?**
Because you had only 2 commands in Moodle310, add-redis-store and add-mem-store that haven't been implemented in later versions, therefore the highest version was always Moodle310.

**Comment by benyovszky** [comment]
/cache/locallib.php is also required by the following commands, so for 4.5 Compatibility, those commands have to be updated as well:
* CacheAddMemStore.php
* CacheAddRedisStore.php
* CacheSet.php

> * the 3 digits problem is something that is happening only when you try to implement add-redis-store for Moodle 4.5.

You try to go in a different way. If you create new commands under /moosh/Moosh/Command/Moodle45/ then you do not need that trick with includes, and that will eliminate your issues. This type of solution was suggested by @tmuras . Of course, your suggestion could also work, but as you recognized, it needs way more change in the code, and it is risky.
