### ISSUE TITLE
Generated code doesn't follow coding style guidelines

### ISSUE THREAD

**Issue by marxjohnson** [tmuras/moosh#6]
[Moodle coding style](http://docs.moodle.org/dev/Coding_style#Indentation) states

> Use an indent of 4 spaces with no tab characters.

However, I just used `moosh generate-form` and `moosh form-add` to generate some code, and found that the code used 2 spaces to indent instead of 4.  For consistency with written code, it would be good to follow the Moodle coding guidelines.

**Comment by tmuras** [comment]
And just 2 years later the bug is fixed.... :)
