### ISSUE TITLE
PHP fatal error when updating to latest version

### ISSUE THREAD

**Issue by cirrus3d** [tmuras/moosh#61]
Hi, I ran:
./composer.phar update
to update to the latest version of moosh (from 0.13).

 I get
  - Updating twig/twig dev-master (27f3e0f => e2d2a25)
    Checking out e2d2a250d963dd5bba4ad23fc01c7282fc042946

and then when running moosh:

PHP Fatal error:  Class 'GetOptionKit\OptionSpecCollection' not found in /root/moosh/moosh.php on line 38

**Comment by tmuras** [comment]
This has been fixed while working on another issue.
