### ISSUE TITLE
Make use of the new Plugins directory API

### ISSUE THREAD

**Issue by mudrd8mz** [tmuras/moosh#73]
There is now a new web service API that moosh might use to get the list of available plugins (instead of the current hackery :-)) The URL of the new service is https://download.moodle.org/api/1.3/pluglist.php and it does not accept any parameters. It's not documented yet but it should be pretty intuitive.

**Comment by mudrd8mz** [comment]
More info at https://tracker.moodle.org/browse/MDLSITE-3217

**Comment by dkns** [comment]
Fixed in 7230b3f9379badace1834b77b28982aa7affc3d1
