### ISSUE TITLE
course-reset does not reset students by default

### ISSUE THREAD

**Issue by rezaies** [tmuras/moosh#80]
the course-reset command does not reset students by default.
workaround:
add the following line after the line that defines the $default variable in file moosh/Moosh/Command/Moodle23/Course/CourseReset.php
`$defaults['unenrol_users'] = array(6);`

**Comment by tmuras** [comment]
@rezaies , I'm planning to do some improvements for this command. Which Moodle version do you use?

**Comment by rezaies** [comment]
used this on 2.6 and 2.7 and 2.8

**Comment by tmuras** [comment]
You can now provide any reset setting you want with -s option. This is implemented for Moodle 2.9.
