### ISSUE TITLE
missing plugins.json error

### ISSUE THREAD

**Issue by usernamenumber** [tmuras/moosh#90]
Using moosh 0.18 installed via apt on Ubuntu Trusty, when I run the plugin-list [example command](http://moosh-online.com/commands/#plugin-list), I get the following warnings, and no other output (same with other plugin names I've tried). 

Maybe the warnings are just because I have PHP's debugging settings set too high, but they look like they could be related to why there are no results. I do have a `~/.moosh` directory, but it's empty. 

```
$ moosh plugin-list quickmail
PHP Warning:  file_get_contents(/u0/brsmith/.moosh/plugins.json): failed to open stream: No such file or directory in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 40

Warning: file_get_contents(/u0/brsmith/.moosh/plugins.json): failed to open stream: No such file or directory in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 40
Can't read json file
```

**Comment by dkns** [comment]
Does this still happen?

**Comment by hcpss-banderson** [comment]
Yes, I am getting this with 0.20 when running ```$ moosh plugin-list```:

```
PHP Warning:  stat(): stat failed for /home/vagrant/.moosh/plugins.json in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 29

Warning: stat(): stat failed for /home/vagrant/.moosh/plugins.json in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 29
PHP Warning:  unlink(/home/vagrant/.moosh/plugins.json): No such file or directory in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 31

Warning: unlink(/home/vagrant/.moosh/plugins.json): No such file or directory in /usr/share/moosh/Moosh/Command/Generic/Plugin/PluginList.php on line 31
```

**Comment by dkns** [comment]
That error should be displayed only the first time you run plug-list command and then it should output list of plugins.

Does it not work for you at all @hcpss-banderson ?

**Comment by hcpss-banderson** [comment]
It works. I had a separate issue that made me think it didn't, but now I see that it does.
