### ISSUE TITLE
Moosh Not working with Moodle 2.8

### ISSUE THREAD

**Issue by bbusschots-nuim** [tmuras/moosh#96]
Even simple Moosh commands do not seem to be working on Moodle 2.8.

As a test, I'm using the command: moosh config-get moodle forgottenpasswordurl

However, every single test fails, I look in the DB, see that a config value is definitely set, run the command, and get back nothing - no error, no answer, just straight back to the command prompt.

I added a debug print statement to the constructor in Moodle23/ConfigGet.php, and that prints, but, when I add a print statement as the second line (after the globals) in execute(), that print never happens, so the command is not even being executed.

Since I am not getting an error message, I have absolutely no idea how I can even start to debug this?

How can I get to the bottom of why the command is not even being executed?

**Comment by bbusschots-nuim** [comment]
By adding in some echo statements I found the exact line where the moosh.php is silently dying:

`$shell_user = posix_getpwuid(posix_geteuid());`

**Comment by bbusschots-nuim** [comment]
The problem was caused by CentOS not installing the PHP POSIX package by default. You'd have thought that a package being missing would generate some sort of sane PHP error, but then again, this is PHP, so maybe not :)

The solution is to install the relevant php-process package, so for people using CentOS 6 with Moodle2.8 that probably means a Webtatic PHP package since CentOS6's native PHP is too old, in my case the solution was:

`yum install php56w-process`

I wonder would it be worth adding a pre-flight check in mosh.php to detect the absence of POSIX support? The POSIX package defines a number of constants, so checking for the presence of one of those could be used as a test.

I'd be happy to submit a pull request with such a pre-flight check if it would be accepted?

**Comment by tmuras** [comment]
It absolutely would be accepted, thanks for troubleshooting it. I'm all for all changes to improve robustness of moosh.

**Comment by dkns** [comment]
Fixed in e4fee536e3c31332835d4d28ac35f555149c7541
